spring:
   application:
      name: nandu-spring-cloud-config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/narendrask89/environment-variable-repo.git
      
server:
  port: ${port:8888}