spring:
  application:
    name: nandu-spring-cloud-api-gateway-service
    
  cloud:
    gateway:
      routes:
      - id: stock-enquiry
        uri: http://localhost:8200/
        predicates:
        - Path=/product-enquiry/**
          
    
server:
  port: ${port:8765}